# Name
portfolio_name = "Simple"
# Path of module
module = "presso.module.portfolio.simple.SimplePortfolio"
# Realtime is true means all DataEvents are generated at the same time
# false means they will be ordered by timestamp
realtime = false
[log]
# Default log level
level = "info"
# Default log path
file = "presso.log"
# Config will be passed to _init() as a dict object
[config]


[[dataevents]]
    name = "bitfinex_kline"
    module = "presso.module.dataevent.bitfinex_kline.BitfinexKlineDataEvent"
    data_path = "https://api.bitfinex.com/v2/candles"
    # All generated DataEvents will be stored as a npy file if the path is not empty
    history_file = "data/history/bitfinex_kline.npy"
    [dataevents.config]
        time_frame = "1m"
        market = "BTCUSD"
        start_time = 1508248900
        end_time = 1508255000

[[dataevents]]
    name = "csv_kline"
    module = "presso.module.dataevent.csv_kline.CsvKlineDataEvent"
    data_path = "data/history/coinbaseUSD_1-min_data_2017-10-20.csv"
    history_file = ""
    [dataevents.config]

#[[dataevents]]
#    name = "npy_kline"
#    module = "presso.module.dataevent.npy_kline.NpyKlineDataEvent"
#    data_path = "data/history/bitfinex_kline.npy"
#    history_file = ""
#    [dataevents.config]


[[alphas]]
    name = "Printer"
    module = "presso.module.alpha.printer.PrinterAlpha"
    # Alpha is triggered by its main DataEvent
    main_dataevent = "bitfinex_kline"
    # Alpha also can access other DataEvents
    dataevents = []
    [alphas.config]


[[connectors]]
    name = "kline_history"
    module = "presso.module.connector.kline_history.KlineHistoryConnector"
    # Connector may use data from DataEvents to calculate price
    dataevents = ["bitfinex_kline",]
    [connectors.config]


[[statistics]]
    name = "Logger"
    module = "presso.module.statistics.logger.LoggerStatistics"
    [statistics.config]
